version: "3.9"
services:
  
  rest:
    image: rest:latest
    build:
      context: .
      dockerfile: ./src/Services/RestService/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: any
  
  grpc:
    image: grpc:latest
    build:
      context: .
      dockerfile: ./src/Services/GrpcService/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: any
  
  webapi:
    image: webapi:latest
    build:
      context: .
      dockerfile: ./src/Web/WebAPI/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1.0'
          memory: 380M
      restart_policy:
        condition: any
  
networks:
  internal:
    name: internal
    driver: bridge