version: "3.9"
services:
  
  rest:
    image: rest:latest
    build:
      context: .
      dockerfile: ./src/Services/REST.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.25'
          memory: 120M
      restart_policy:
        condition: any
  
  grpc:
    image: grpc:latest
    build:
      context: .
      dockerfile: ./src/Services/gRPC.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: '0.25'
          memory: 120M
      restart_policy:
        condition: any
  
  webapi:
    image: webapi:latest
    build:
      context: .
      dockerfile: ./src/Web/BFF.WebAPI/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:5001;http://*:5000;https://*:443;http://*:80
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
      - "5000:5000"
      - "5001:5001"
    networks:
      - internal
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 250M
      restart_policy:
        condition: any

networks:
  internal:
    name: internal
    driver: bridge