version: "3.9"
services:
  
  rest:
    image: rest:latest
    build:
      context: .
      dockerfile: ./src/Services/REST.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: any
  
  grpc:
    image: grpc:latest
    build:
      context: .
      dockerfile: ./src/Services/gRPC.WebApi/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80;
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '1.0'
          memory: 256M
      restart_policy:
        condition: any
  
  webapi:
    image: webapi:latest
    build:
      context: .
      dockerfile: ./src/Web/BFF.WebAPI/Dockerfile
    environment:
      ASPNETCORE_URLS: https://*:443;http://*:80
      ASPNETCORE_ENVIRONMENT: Staging
    ports:
      - "80"
      - "443"
    networks:
      - internal
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 380M
      restart_policy:
        condition: any
  
#   proxy:
#     container_name: proxy
#     image: nginx:alpine
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       webapi:
#         condition: service_started
#       grpc:
#         condition: service_started
#     ports:
#       - "5555"
#       - "6666"
#     networks:
#       - internal
#     deploy:
# #      resources:
# #        limits:
# #          cpus: 1
# #          memory: 80M
#       restart_policy:
#         condition: any

networks:
  internal:
    name: internal
    driver: bridge